In [38]:
import pandas as pd
base = pd.read_csv('house_prices.csv')
base.head()

,id,date,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,...,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long,sqft_living15,sqft_lot15
0,7129300520,20141013T000000,221900.0,3,1.00,1180,5650,1.0,0,0,...,7,1180,0,1955,0,98178,47.5112,-122.257,1340,5650
1,6414100192,20141209T000000,538000.0,3,2.25,2570,7242,2.0,0,0,...,7,2170,400,1951,1991,98125,47.7210,-122.319,1690,7639
2,5631500400,20150225T000000,180000.0,2,1.00,770,10000,1.0,0,0,...,6,770,0,1933,0,98028,47.7379,-122.233,2720,8062
3,2487200875,20141209T000000,604000.0,4,3.00,1960,5000,1.0,0,0,...,7,1050,910,1965,0,98136,47.5208,-122.393,1360,5000
4,1954400510,20150218T000000,510000.0,3,2.00,1680,8080,1.0,0,0,...,8,1680,0,1987,0,98074,47.6168,-122.045,1800,7503

In [39]:
base.columns

Index(['id', 'date', 'price', 'bedrooms', 'bathrooms', 'sqft_living',
       'sqft_lot', 'floors', 'waterfront', 'view', 'condition', 'grade',
       'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated', 'zipcode',
       'lat', 'long', 'sqft_living15', 'sqft_lot15'],
      dtype='object')

In [40]:
base.drop(['id', 'date', 'sqft_living15', 'sqft_lot15'], axis=1, inplace=True)

In [41]:
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler()
base[['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 
'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 
'yr_renovated', 'zipcode', 'lat', 'long']] = scaler_x.fit_transform(base[['bedrooms', 'bathrooms', 'sqft_living', 'sqft_lot', 
'floors', 'waterfront', 'view', 'condition', 'grade', 'sqft_above', 'sqft_basement', 'yr_built', 
'yr_renovated', 'zipcode', 'lat', 'long']])

In [42]:
base.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,221900.0,0.090909,0.12500,0.067170,0.003108,0.0,0.0,0.0,0.5,0.500000,0.097588,0.000000,0.478261,0.000000,0.893939,0.571498,0.217608
1,538000.0,0.090909,0.28125,0.172075,0.004072,0.4,0.0,0.0,0.5,0.500000,0.206140,0.082988,0.443478,0.988089,0.626263,0.908959,0.166113
2,180000.0,0.060606,0.12500,0.036226,0.005743,0.0,0.0,0.0,0.5,0.416667,0.052632,0.000000,0.286957,0.000000,0.136364,0.936143,0.237542
3,604000.0,0.121212,0.37500,0.126038,0.002714,0.0,0.0,0.0,1.0,0.500000,0.083333,0.188797,0.565217,0.000000,0.681818,0.586939,0.104651
4,510000.0,0.090909,0.25000,0.104906,0.004579,0.0,0.0,0.0,0.5,0.583333,0.152412,0.000000,0.756522,0.000000,0.368687,0.741354,0.393688

In [43]:
scaler_y = MinMaxScaler()
base[['price']] = scaler_y.fit_transform(base[['price']])

In [44]:
base.head()

,price,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,0.019266,0.090909,0.12500,0.067170,0.003108,0.0,0.0,0.0,0.5,0.500000,0.097588,0.000000,0.478261,0.000000,0.893939,0.571498,0.217608
1,0.060721,0.090909,0.28125,0.172075,0.004072,0.4,0.0,0.0,0.5,0.500000,0.206140,0.082988,0.443478,0.988089,0.626263,0.908959,0.166113
2,0.013770,0.060606,0.12500,0.036226,0.005743,0.0,0.0,0.0,0.5,0.416667,0.052632,0.000000,0.286957,0.000000,0.136364,0.936143,0.237542
3,0.069377,0.121212,0.37500,0.126038,0.002714,0.0,0.0,0.0,1.0,0.500000,0.083333,0.188797,0.565217,0.000000,0.681818,0.586939,0.104651
4,0.057049,0.090909,0.25000,0.104906,0.004579,0.0,0.0,0.0,0.5,0.583333,0.152412,0.000000,0.756522,0.000000,0.368687,0.741354,0.393688

In [45]:
x = base.drop('price', axis = 1)
x.head()

,bedrooms,bathrooms,sqft_living,sqft_lot,floors,waterfront,view,condition,grade,sqft_above,sqft_basement,yr_built,yr_renovated,zipcode,lat,long
0,0.090909,0.12500,0.067170,0.003108,0.0,0.0,0.0,0.5,0.500000,0.097588,0.000000,0.478261,0.000000,0.893939,0.571498,0.217608
1,0.090909,0.28125,0.172075,0.004072,0.4,0.0,0.0,0.5,0.500000,0.206140,0.082988,0.443478,0.988089,0.626263,0.908959,0.166113
2,0.060606,0.12500,0.036226,0.005743,0.0,0.0,0.0,0.5,0.416667,0.052632,0.000000,0.286957,0.000000,0.136364,0.936143,0.237542
3,0.121212,0.37500,0.126038,0.002714,0.0,0.0,0.0,1.0,0.500000,0.083333,0.188797,0.565217,0.000000,0.681818,0.586939,0.104651
4,0.090909,0.25000,0.104906,0.004579,0.0,0.0,0.0,0.5,0.583333,0.152412,0.000000,0.756522,0.000000,0.368687,0.741354,0.393688

In [46]:
y = base.price
y.head()
type(y)

pandas.core.series.Series

In [47]:
columns_predictors = base.columns[3:]
columns_predictors

Index(['sqft_living', 'sqft_lot', 'floors', 'waterfront', 'view', 'condition',
       'grade', 'sqft_above', 'sqft_basement', 'yr_built', 'yr_renovated',
       'zipcode', 'lat', 'long'],
      dtype='object')

In [48]:
import tensorflow as tf

In [49]:
columns  = [tf.feature_column.numeric_column(key = name) for name in columns_predictors]

In [50]:
from sklearn.model_selection import train_test_split
train_x, test_x, train_y, test_y = train_test_split(x, y, test_size = 0.3)

In [51]:
def make_input_fn(x, y = None, num_epochs = None, shuffle = True, batch_size = 32):
    def input_function():
        ds = tf.data.Dataset.from_tensor_slices((dict(x), y))
        if shuffle:
            ds = ds.shuffle(1000)
        ds = ds.batch(batch_size).repeat(num_epochs)
        return ds
    return input_function

In [52]:
ds = tf.data.Dataset.from_tensor_slices((dict(train_x), train_y))
ds

<TensorSliceDataset shapes: ({bedrooms: (), bathrooms: (), sqft_living: (), sqft_lot: (), floors: (), waterfront: (), view: (), condition: (), grade: (), sqft_above: (), sqft_basement: (), yr_built: (), yr_renovated: (), zipcode: (), lat: (), long: ()}, ()), types: ({bedrooms: tf.float64, bathrooms: tf.float64, sqft_living: tf.float64, sqft_lot: tf.float64, floors: tf.float64, waterfront: tf.float64, view: tf.float64, condition: tf.float64, grade: tf.float64, sqft_above: tf.float64, sqft_basement: tf.float64, yr_built: tf.float64, yr_renovated: tf.float64, zipcode: tf.float64, lat: tf.float64, long: tf.float64}, tf.float64)>

In [53]:
train_function = make_input_fn(train_x, train_y)

In [54]:
train_function()

<RepeatDataset shapes: ({bedrooms: (None,), bathrooms: (None,), sqft_living: (None,), sqft_lot: (None,), floors: (None,), waterfront: (None,), view: (None,), condition: (None,), grade: (None,), sqft_above: (None,), sqft_basement: (None,), yr_built: (None,), yr_renovated: (None,), zipcode: (None,), lat: (None,), long: (None,)}, (None,)), types: ({bedrooms: tf.float64, bathrooms: tf.float64, sqft_living: tf.float64, sqft_lot: tf.float64, floors: tf.float64, waterfront: tf.float64, view: tf.float64, condition: tf.float64, grade: tf.float64, sqft_above: tf.float64, sqft_basement: tf.float64, yr_built: tf.float64, yr_renovated: tf.float64, zipcode: tf.float64, lat: tf.float64, long: tf.float64}, tf.float64)>

In [55]:
regressor = tf.estimator.LinearRegressor(feature_columns = columns)

INFO:tensorflow:Using default config.
WARNING:tensorflow:Using temporary folder as model directory: C:\Users\Matheus\AppData\Local\Temp\tmpql7bfw2q
INFO:tensorflow:Using config: {'_model_dir': 'C:\\Users\\Matheus\\AppData\\Local\\Temp\\tmpql7bfw2q', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}

In [56]:
regressor.train(input_fn = train_function, steps = 10000)

INFO:tensorflow:Calling model_fn.

C:\Users\Matheus\.conda\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1700: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into C:\Users\Matheus\AppData\Local\Temp\tmpql7bfw2q\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 0.0036444145, step = 0
INFO:tensorflow:global_step/sec: 766.286
INFO:tensorflow:loss = 0.0015515499, step = 100 (0.132 sec)
INFO:tensorflow:global_step/sec: 1398.6
INFO:tensorflow:loss = 0.0005338957, step = 200 (0.071 sec)
INFO:tensorflow:global_step/sec: 1408.43
INFO:tensorflow:loss = 0.0007770108, step = 300 (0.071 sec)
INFO:tensorflow:global_step/sec: 1379.34
INFO:tensorflow:loss = 0.0019891914, step = 400 (0.073 sec)
INFO:tensorflow:global_step/sec: 1398.59
INFO:tensorflow:loss = 0.00085324247, step = 500 (0.072 sec)
INFO:tensorflow:global_step/sec: 1298.69
INFO:tensorflow:loss = 0.000116001946, step = 600 (0.077 sec)
INFO:tensorflow:global_step/sec: 1333.34
INFO:tensorflow:loss = 0.0017359967, step = 700 (0.075 sec)
INFO:tensorflow:global_step/sec: 1379.32
INFO:tensorflow:loss = 0.0010678913, step = 800 (0.072 sec)
INFO:tensorflow:global_step/sec: 1388.86
INFO:tensorflow:loss = 0.00051262876, step = 900 (0.073 sec)
INFO:tensorflow:global_step/sec: 1342.29
INFO:tensorflow:loss = 0.00060357916, step = 1000 (0.074 sec)
INFO:tensorflow:global_step/sec: 1351.36
INFO:tensorflow:loss = 0.00033902528, step = 1100 (0.074 sec)
INFO:tensorflow:global_step/sec: 1369.86
INFO:tensorflow:loss = 0.00035250856, step = 1200 (0.073 sec)
INFO:tensorflow:global_step/sec: 1342.3
INFO:tensorflow:loss = 0.000554074, step = 1300 (0.075 sec)
INFO:tensorflow:global_step/sec: 1418.42
INFO:tensorflow:loss = 0.0016565382, step = 1400 (0.071 sec)
INFO:tensorflow:global_step/sec: 1398.53
INFO:tensorflow:loss = 0.00072871556, step = 1500 (0.071 sec)
INFO:tensorflow:global_step/sec: 1398.67
INFO:tensorflow:loss = 0.0016412667, step = 1600 (0.072 sec)
INFO:tensorflow:global_step/sec: 1379.32
INFO:tensorflow:loss = 0.00016541602, step = 1700 (0.072 sec)
INFO:tensorflow:global_step/sec: 1398.62
INFO:tensorflow:loss = 0.000263484, step = 1800 (0.072 sec)
INFO:tensorflow:global_step/sec: 1379.29
INFO:tensorflow:loss = 0.00030546612, step = 1900 (0.072 sec)
INFO:tensorflow:global_step/sec: 1369.86
INFO:tensorflow:loss = 0.0027956213, step = 2000 (0.073 sec)
INFO:tensorflow:global_step/sec: 1315.79
INFO:tensorflow:loss = 0.0005180879, step = 2100 (0.076 sec)
INFO:tensorflow:global_step/sec: 1379.32
INFO:tensorflow:loss = 0.00024589105, step = 2200 (0.073 sec)
INFO:tensorflow:global_step/sec: 1388.86
INFO:tensorflow:loss = 0.0008627102, step = 2300 (0.072 sec)
INFO:tensorflow:global_step/sec: 1379.35
INFO:tensorflow:loss = 0.0012503448, step = 2400 (0.072 sec)
INFO:tensorflow:global_step/sec: 1388.87
INFO:tensorflow:loss = 0.0010167034, step = 2500 (0.073 sec)
INFO:tensorflow:global_step/sec: 1379.32
INFO:tensorflow:loss = 0.0006030541, step = 2600 (0.072 sec)
INFO:tensorflow:global_step/sec: 1351.31
INFO:tensorflow:loss = 0.00081603834, step = 2700 (0.074 sec)
INFO:tensorflow:global_step/sec: 1379.35
INFO:tensorflow:loss = 0.00018144978, step = 2800 (0.072 sec)
INFO:tensorflow:global_step/sec: 1282.03
INFO:tensorflow:loss = 0.00051394495, step = 2900 (0.078 sec)
INFO:tensorflow:global_step/sec: 1234.57
INFO:tensorflow:loss = 0.00087852206, step = 3000 (0.081 sec)
INFO:tensorflow:global_step/sec: 1234.57
INFO:tensorflow:loss = 0.0010479509, step = 3100 (0.081 sec)
INFO:tensorflow:global_step/sec: 1250.01
INFO:tensorflow:loss = 0.0005113472, step = 3200 (0.080 sec)
INFO:tensorflow:global_step/sec: 1265.82
INFO:tensorflow:loss = 0.0008410243, step = 3300 (0.079 sec)
INFO:tensorflow:global_step/sec: 1183.45
INFO:tensorflow:loss = 0.0006038363, step = 3400 (0.085 sec)
INFO:tensorflow:global_step/sec: 1226.99
INFO:tensorflow:loss = 0.00036626443, step = 3500 (0.082 sec)
INFO:tensorflow:global_step/sec: 1333.32
INFO:tensorflow:loss = 0.0012212354, step = 3600 (0.075 sec)
INFO:tensorflow:global_step/sec: 1360.55
INFO:tensorflow:loss = 0.00037154864, step = 3700 (0.074 sec)
INFO:tensorflow:global_step/sec: 1398.6
INFO:tensorflow:loss = 0.00045133385, step = 3800 (0.072 sec)
INFO:tensorflow:global_step/sec: 1360.54
INFO:tensorflow:loss = 0.0040597743, step = 3900 (0.073 sec)
INFO:tensorflow:global_step/sec: 1418.45
INFO:tensorflow:loss = 0.00044778024, step = 4000 (0.071 sec)
INFO:tensorflow:global_step/sec: 1398.53
INFO:tensorflow:loss = 0.0010671753, step = 4100 (0.071 sec)
INFO:tensorflow:global_step/sec: 1408.49
INFO:tensorflow:loss = 0.001128601, step = 4200 (0.071 sec)
INFO:tensorflow:global_step/sec: 1398.61
INFO:tensorflow:loss = 0.00043903184, step = 4300 (0.072 sec)
INFO:tensorflow:global_step/sec: 1388.88
INFO:tensorflow:loss = 0.0002507523, step = 4400 (0.072 sec)
INFO:tensorflow:global_step/sec: 1351.34
INFO:tensorflow:loss = 0.00040773104, step = 4500 (0.074 sec)
INFO:tensorflow:global_step/sec: 1379.33
INFO:tensorflow:loss = 0.00037793326, step = 4600 (0.072 sec)
INFO:tensorflow:global_step/sec: 1342.29
INFO:tensorflow:loss = 0.0007893256, step = 4700 (0.075 sec)
INFO:tensorflow:global_step/sec: 1351.34
INFO:tensorflow:loss = 0.00061941287, step = 4800 (0.074 sec)
INFO:tensorflow:global_step/sec: 1379.28
INFO:tensorflow:loss = 0.0014669829, step = 4900 (0.072 sec)
INFO:tensorflow:global_step/sec: 1369.9
INFO:tensorflow:loss = 0.0008198705, step = 5000 (0.073 sec)
INFO:tensorflow:global_step/sec: 1379.28
INFO:tensorflow:loss = 0.00031873886, step = 5100 (0.073 sec)
INFO:tensorflow:global_step/sec: 1369.84
INFO:tensorflow:loss = 0.0005176886, step = 5200 (0.072 sec)
INFO:tensorflow:global_step/sec: 1333.38
INFO:tensorflow:loss = 0.0028804988, step = 5300 (0.076 sec)
INFO:tensorflow:global_step/sec: 1360.55
INFO:tensorflow:loss = 0.00035132904, step = 5400 (0.073 sec)
INFO:tensorflow:global_step/sec: 1315.77
INFO:tensorflow:loss = 0.00034077768, step = 5500 (0.076 sec)
INFO:tensorflow:global_step/sec: 1388.89
INFO:tensorflow:loss = 0.0005596116, step = 5600 (0.072 sec)
INFO:tensorflow:global_step/sec: 1360.56
INFO:tensorflow:loss = 0.00021230252, step = 5700 (0.074 sec)
INFO:tensorflow:global_step/sec: 1388.9
INFO:tensorflow:loss = 0.0005735095, step = 5800 (0.072 sec)
INFO:tensorflow:global_step/sec: 1408.45
INFO:tensorflow:loss = 0.0005165908, step = 5900 (0.072 sec)
INFO:tensorflow:global_step/sec: 1398.61
INFO:tensorflow:loss = 0.00039025056, step = 6000 (0.071 sec)
INFO:tensorflow:global_step/sec: 1369.86
INFO:tensorflow:loss = 0.0005313909, step = 6100 (0.074 sec)
INFO:tensorflow:global_step/sec: 1388.86
INFO:tensorflow:loss = 0.0006443834, step = 6200 (0.072 sec)
INFO:tensorflow:global_step/sec: 1408.42
INFO:tensorflow:loss = 0.0004921941, step = 6300 (0.071 sec)
INFO:tensorflow:global_step/sec: 1398.66
INFO:tensorflow:loss = 0.00056034647, step = 6400 (0.072 sec)
INFO:tensorflow:global_step/sec: 1408.46
INFO:tensorflow:loss = 0.00057136547, step = 6500 (0.071 sec)
INFO:tensorflow:global_step/sec: 1418.42
INFO:tensorflow:loss = 0.0006140825, step = 6600 (0.070 sec)
INFO:tensorflow:global_step/sec: 1398.6
INFO:tensorflow:loss = 0.0003160795, step = 6700 (0.072 sec)
INFO:tensorflow:global_step/sec: 1408.46
INFO:tensorflow:loss = 0.00068353396, step = 6800 (0.071 sec)
INFO:tensorflow:global_step/sec: 1408.44
INFO:tensorflow:loss = 0.00039092035, step = 6900 (0.071 sec)
INFO:tensorflow:global_step/sec: 1408.45
INFO:tensorflow:loss = 0.0004228994, step = 7000 (0.071 sec)
INFO:tensorflow:global_step/sec: 1398.57
INFO:tensorflow:loss = 0.00035423052, step = 7100 (0.072 sec)
INFO:tensorflow:global_step/sec: 1408.51
INFO:tensorflow:loss = 0.0009435206, step = 7200 (0.071 sec)
INFO:tensorflow:global_step/sec: 1369.83
INFO:tensorflow:loss = 0.0006095123, step = 7300 (0.073 sec)
INFO:tensorflow:global_step/sec: 1226.98
INFO:tensorflow:loss = 0.00088665, step = 7400 (0.082 sec)
INFO:tensorflow:global_step/sec: 1219.54
INFO:tensorflow:loss = 0.0006655646, step = 7500 (0.082 sec)
INFO:tensorflow:global_step/sec: 1226.98

INFO:tensorflow:loss = 0.0005253728, step = 7600 (0.082 sec)
INFO:tensorflow:global_step/sec: 1257.87
INFO:tensorflow:loss = 0.00091095566, step = 7700 (0.079 sec)
INFO:tensorflow:global_step/sec: 1242.23
INFO:tensorflow:loss = 0.0007034643, step = 7800 (0.081 sec)
INFO:tensorflow:global_step/sec: 1234.52
INFO:tensorflow:loss = 0.00035228534, step = 7900 (0.081 sec)
INFO:tensorflow:global_step/sec: 1250.03
INFO:tensorflow:loss = 0.0010218432, step = 8000 (0.080 sec)
INFO:tensorflow:global_step/sec: 1219.48
INFO:tensorflow:loss = 0.0010992168, step = 8100 (0.082 sec)
INFO:tensorflow:global_step/sec: 1234.61
INFO:tensorflow:loss = 0.0023777068, step = 8200 (0.081 sec)
INFO:tensorflow:global_step/sec: 1242.23
INFO:tensorflow:loss = 0.00078923296, step = 8300 (0.080 sec)
INFO:tensorflow:global_step/sec: 1250.01
INFO:tensorflow:loss = 0.0004181562, step = 8400 (0.081 sec)
INFO:tensorflow:global_step/sec: 1273.83
INFO:tensorflow:loss = 0.00025851373, step = 8500 (0.078 sec)
INFO:tensorflow:global_step/sec: 1212.17
INFO:tensorflow:loss = 0.0003621146, step = 8600 (0.082 sec)
INFO:tensorflow:global_step/sec: 1219.53
INFO:tensorflow:loss = 0.00019328864, step = 8700 (0.082 sec)
INFO:tensorflow:global_step/sec: 1183.39
INFO:tensorflow:loss = 0.00042695616, step = 8800 (0.084 sec)
INFO:tensorflow:global_step/sec: 1204.82
INFO:tensorflow:loss = 0.001374594, step = 8900 (0.083 sec)
INFO:tensorflow:global_step/sec: 1290.36
INFO:tensorflow:loss = 0.0012337249, step = 9000 (0.077 sec)
INFO:tensorflow:global_step/sec: 1324.48
INFO:tensorflow:loss = 0.00042230572, step = 9100 (0.075 sec)
INFO:tensorflow:global_step/sec: 1219.54
INFO:tensorflow:loss = 0.0004790468, step = 9200 (0.082 sec)
INFO:tensorflow:global_step/sec: 1257.83
INFO:tensorflow:loss = 0.00041511227, step = 9300 (0.080 sec)
INFO:tensorflow:global_step/sec: 1333.35
INFO:tensorflow:loss = 0.00082111324, step = 9400 (0.075 sec)
INFO:tensorflow:global_step/sec: 1428.59
INFO:tensorflow:loss = 0.0005117161, step = 9500 (0.070 sec)
INFO:tensorflow:global_step/sec: 1298.69
INFO:tensorflow:loss = 0.00039229885, step = 9600 (0.077 sec)
INFO:tensorflow:global_step/sec: 1369.82
INFO:tensorflow:loss = 0.00073679606, step = 9700 (0.073 sec)
INFO:tensorflow:global_step/sec: 1398.64
INFO:tensorflow:loss = 0.0003868356, step = 9800 (0.072 sec)
INFO:tensorflow:global_step/sec: 1388.88
INFO:tensorflow:loss = 0.00052102807, step = 9900 (0.072 sec)
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 10000...
INFO:tensorflow:Saving checkpoints for 10000 into C:\Users\Matheus\AppData\Local\Temp\tmpql7bfw2q\model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 10000...
INFO:tensorflow:Loss for final step: 0.0015543263.

In [57]:
train_metrics = regressor.evaluate(input_fn = train_function, steps = 10000)

INFO:tensorflow:Calling model_fn.

C:\Users\Matheus\.conda\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1700: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-03-01T23:29:11
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Matheus\AppData\Local\Temp\tmpql7bfw2q\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Inference Time : 6.03500s
INFO:tensorflow:Finished evaluation at 2022-03-01-23:29:17
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.0007039909, global_step = 10000, label/mean = 0.061226845, loss = 0.0007039606, prediction/mean = 0.0642606
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 10000: C:\Users\Matheus\AppData\Local\Temp\tmpql7bfw2q\model.ckpt-10000

In [58]:
test_function = make_input_fn(test_x, test_y, num_epochs = 10000, shuffle = False)

In [59]:
test_metrics = regressor.evaluate(input_fn = test_function, steps = 10000)

INFO:tensorflow:Calling model_fn.

C:\Users\Matheus\.conda\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1700: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Starting evaluation at 2022-03-01T23:29:19
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Matheus\AppData\Local\Temp\tmpql7bfw2q\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Evaluation [1000/10000]
INFO:tensorflow:Evaluation [2000/10000]
INFO:tensorflow:Evaluation [3000/10000]
INFO:tensorflow:Evaluation [4000/10000]
INFO:tensorflow:Evaluation [5000/10000]
INFO:tensorflow:Evaluation [6000/10000]
INFO:tensorflow:Evaluation [7000/10000]
INFO:tensorflow:Evaluation [8000/10000]
INFO:tensorflow:Evaluation [9000/10000]
INFO:tensorflow:Evaluation [10000/10000]
INFO:tensorflow:Inference Time : 5.20808s
INFO:tensorflow:Finished evaluation at 2022-03-01-23:29:24
INFO:tensorflow:Saving dict for global step 10000: average_loss = 0.00077698106, global_step = 10000, label/mean = 0.060446717, loss = 0.0007782419, prediction/mean = 0.06384087
INFO:tensorflow:Saving 'checkpoint_path' summary for global step 10000: C:\Users\Matheus\AppData\Local\Temp\tmpql7bfw2q\model.ckpt-10000

In [60]:
print(test_metrics)

{'average_loss': 0.00077698106, 'label/mean': 0.060446717, 'loss': 0.0007782419, 'prediction/mean': 0.06384087, 'global_step': 10000}

In [61]:
predict_function = make_input_fn(test_x, num_epochs = 1, shuffle = False)

In [62]:
predicts = regressor.predict(input_fn = predict_function)

In [63]:
predicts_results = []
for predict in regressor.predict(input_fn = predict_function):
    predicts_results.append(predict['predictions'])

INFO:tensorflow:Calling model_fn.

C:\Users\Matheus\.conda\envs\machine_learning\lib\site-packages\tensorflow\python\keras\engine\base_layer_v1.py:1700: UserWarning: `layer.add_variable` is deprecated and will be removed in a future version. Please use `layer.add_weight` method instead.
  warnings.warn('`layer.add_variable` is deprecated and '

INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from C:\Users\Matheus\AppData\Local\Temp\tmpql7bfw2q\model.ckpt-10000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.

In [64]:
import numpy as np
predicts_results = np.asarray(predicts_results).reshape(-1, 1)

In [65]:
predicts_results = scaler_y.inverse_transform(predicts_results)
y_results = test_y.values.reshape(-1, 1)
y_results = scaler_y.inverse_transform(y_results)

In [66]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(y_results, predicts_results)

In [67]:
mae

132026.5489869821